import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.scss";
import { Button } from "./ui/Button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sinaloa = localFont({
  src: [
    {
      path: "../public/fonts/Sinaloa_.ttf",
      weight: "400",
    },
  ],
  variable: "--font-sinaloa",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-7xl mx-auto md:p-9 p-4 `}>
        <nav className="md:mb-20 mb-10 md:pb-9 md:border-b border-black flex flex-col md:flex-row items-center justify-between content-center">
          <span className={`${sinaloa.className} text-2xl`}>Compilado B</span>
          <div className="md:flex gap-2 hidden ">
            <Button text="<- #18" secondary></Button>
            <Button text="#16 ->" secondary></Button>
          </div>
        </nav>
        {children}
        <footer className="mt-24 border-t border-black pt-10">
          <div className="flex justify-between">
            <div className="md:w-1/3">
              <div className={`${sinaloa.className} text-2xl mb-4`}>
                Compilado B
              </div>
              <p className="text-xs">
                Este é um site independente e nao relacionado ao podcast
                <br />
                <i>Vamos Falar Sobre Música.</i> <br />
                <br />
                Ajude o podcast como puder.
              </p>
              <div className="mt-4 flex gap-2">
                <Button text="Spotify" />
                <Button text="Website" secondary />
              </div>
            </div>
            <div className="md:flex gap-2 hidden ">
              <Button text="<- #18" secondary></Button>
              <Button text="#16 ->" secondary></Button>
            </div>
          </div>
          <div className="text-xs font-light opacity-75 mt-4">
            Ⓒ 2023 - Feito com 🤘 por Bernardo Bechtold
          </div>
        </footer>
      </body>
    </html>
  );
}
